/**
 * Eine Liste von möglichen Sublines für die Startseite.
 * Diese werden zufällig ausgewählt, wenn die Startkomponente initialisiert wird.
 */
export const SUBLINES = [
  'Wir trinken im Schatten, während der Vorstand sich abrackert',
  'Ohne uns habt ihr eh kein Spaß',
  "Weil wir's können",
  "Weil wir's besser können",
  "Weil wir's einfach besser können",
  'Arbeiten lassen war noch nie so einfach',
  'Wir bringen den Spaß, ihr die Formalitäten',
  'Mehr Bier, weniger Bürokratie',
  'Tradition trifft Gelassenheit',
  'Wir sind der Grund, warum’s überhaupt läuft',
  'Wo andere ackern, lehnen wir zurück',
  'Offiziell unoffiziell die Besten',
  'Mit Stil statt mit Stempel',
  'Wenn Chaos Klasse hat',
  'Wir nehmen uns nix – außer Zeit',
  'Mehr Bier, weniger Tagesordnungspunkte',
  'Unser Geschäftsbericht hat nur eine Zahl: Promille',
  'Vorstand klingt nach Verantwortung – wir nach Vergnügen',
  'Wenn der Vorstand redet, bestellen wir schon die nächste Runde',
  'Wo der Vorstand ackert, feiern wir Fortschritt',
  'Der Vorstand macht Pläne, wir machen Party',
  'Protokolle enden, Legenden bleiben',
  'Der Vorstand diskutiert – wir liefern Resultate: leergetrunkene Kästen',
  'Sitzungen bis Mitternacht? Wir sitzen bis Mitternacht – an der Bar',
  'Vorstandsarbeit klingt nach Stress, wir klingen nach Spaß',
  'Während der Vorstand Ordnung schafft, schaffen wir Unordnung',
  'Euer Albtraum unser Highlight: die Jahreshauptversammlung',
  'Wir haben keine Ämter, nur bessere Geschichten',
  'Wenn der Vorstand die Welt rettet, retten wir das Fass',
  'Der Vorstand plant die Zukunft, wir genießen die Gegenwart',
  'Man sagt: Die Landjugend braucht Struktur – wir sagen: Die Landjugend braucht Bier',
  'Der Vorstand organisiert die Zukunft, wir die Afterparty',
  'In der Landjugend kann man wählen: Vorstand oder Vollsuff',
  'Vorstand: PowerPoint. Wir: Bier',
  'Die reden über Vereinsbeiträge, wir über Restbestände',
  'In der Landjugend gibt’s zwei Sorten Menschen: die im Protokoll und die im Rausch',
  'Ohne Vorstand kein Verein – ohne uns keine Feier',
  'In der Landjugend darf jeder mal Vorstand spielen – wir bleiben lieber Stammgäste',
  'Der Vorstand redet von Ordnung, wir von Nachschub',
  'Vorstand? Klingt nach Pflicht. Wir nach Absturz',
  'Während der Vorstand die Kassen prüft, prüfen wir die Fässer',
  'Ohne Vorstand gibt’s keinen Verein – ohne uns kein Leben in der Bude',
  'Vorstand träumt von Ordnung – wir träumen vom Frühschoppen',
];
