export const BEITRITTS_GRUENDE = {
  aufgenommen: [
    'Humor stimmt, Zapfhahn-Kenntnisse top',
    'Kann mit uns lachen – passt perfekt',
    'Trinkfestigkeit und Schlagfertigkeit vorhanden',
    'Hat sofort die richtige Einstellung fürs Chaos',
    'Formular korrekt ausgefüllt, Persönlichkeit überprüft – bestanden',
    'Legt die Füße hoch, denkt aber mit – genau unser Typ',
    'Passt in die Runde wie Bier ins Glas',
    'Hat den ersten Test am Biertisch bestanden',
    'Charme + Humor = Ja!',
    'Hat beim Bierdeckel-Duell gewonnen – direkt aufgenommen',
    'Humor passt, top',
    'Kann mit uns über den Vorstand lachen – perfekt!',
    'Trinkfestigkeit und Kreativität am Zapfhahn vorhanden',
    'Formular korrekt, Persönlichkeit legendär',
    'Hat sofort die richtigen Sprüche rausgehauen – willkommen!',
    'Chaos-tauglich, Feier-tauglich, Mensch-tauglich',
    'Legt Gläser auf die richtige Seite – Aufnahme bestätigt',
    'Redet nicht von Regeln, redet von Gläsern und Spaß',
    'Kann gleichzeitig lachen und Bier balancieren – episch',
    'Wir haben uns alle gut amüsiert – Aufnahme klar!',
    'Hat den ersten Test am Tresen souverän bestanden',
    'Humor-Level: Meisterklasse, Gläser-Level: ebenfalls',
    'Konnte spontan ein Getränk mischen – direkt in die Runde',
  ],
  abgelehnt: [
    'Trinkt nur Wasser… schwer aufzunehmen',
    'Humor nicht kompatibel, besser draußen bleiben',
    'Formular korrekt, Persönlichkeit mangelhaft',
    'Redet zu viel vom Vorstand – nicht passend',
    'Hat den ersten Test am Biertisch nicht bestanden',
    'Zu ernst – sorry, nächstes Mal',
    'Schlägt beim Lachen daneben – leider abgelehnt',
    'Nicht auf unserem Level – besser draußen warten',
    'Trinkt nur Wasser – versuchs mal mit Wacholder',
    'Redet zu viel über Verantwortung – nicht unser Stil',
    'Zapfhahn-Fähigkeiten unterirdisch – sorry',
    'Humor-Check fehlgeschlagen – besser draußen warten',
    'Formular perfekt, Persönlichkeit mau',
    'Zu ernst, zu brav, zu langweilig',
    'Lacht nicht, kritisiert nur – leider nein',
    'Denkt zu viel an Regeln, zu wenig an Spaß',
    'Hat den ersten Test am Tresen verkackt',
    'Kann Gläser nicht balancieren – Sicherheitsrisiko',
    'Vorstandswitze verstanden? Nein. Aufnahme: Nein.',
    'Redet nur über Paragraphen, nicht über Promille',
    'Humor-Level: Offline – wir bleiben hart',
  ],
};
